# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft / Fabric 26.2
minecraft_version=26.2-rc-2
loader_version=0.19.3
fabric_version=0.152.0+26.2
loom_version=1.16-SNAPSHOT
java_version=25

# Mod
mod_id=create_enchantment_industry
mod_artifact_id=create-enchantment-industry
mod_name=Create: Enchantment Industry
mod_license=LGPL-3.0-or-later
mod_version=2.4.2+fabric.26.2-dev.1
mod_group_id=plus.dragons.createenchantmentindustry
mod_authors=DragonsPlus
mod_description=Enchantment, Experience, Enhancement and Enlightening - with Create
mod_github=https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry

# Create Fly reference
create_version=6.0.9
create_fly_build=1
